name: Sample App Conainerization and Deployment

on: [push]
env:
  DOCKER_USER_NAME: ${{secrets.DOCKER_USER_NAME}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: amaresh1995


jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: |
        docker login -u $DOCKER_USER_NAME -p $DOCKER_PASS

    - name: Build Docker file
      run: docker build . --file Dockerfile --tag $DOCKER_USER_NAME/$REPO_NAME:$GITHUB_SHA

    - name: Docker Push
      run: docker push $DOCKER_USER_NAME/$REPO_NAME:$GITHUB_SHA
